# Introduction to matplotlib


## Introduction

The matplotlib library is used to visualize data in a way to help others understand data, especially for large datasets. A variety of graphs can be made in both 2D and 3D. Matplotlib can also produce animations which can be used on graphical applications.


## How to Use

The module is not a default package to Python. Therefore, users will need to install using either Anaconda or pip.

Within the library are many functions and submodules that can be used depending on the purpose of the visualization. For this chapter, a progression series will be done on a randomly generated dataset in order to provide a comprehensive look into the visual elements that may be used for the graphs.

```{python}

import numpy as np
import matplotlib.pyplot as plt

np.random.seed(8465);

x = np.random.rand(0,3,20);
y = np.random.rand(0,3,20);
z = np.random.rand(0,3,20);

plt.scatter(x,y)
plt.show()

```

## Animation

The animation submodule in matplotlib can simulate data.

## Conclusion

Put sumaries here.
